liip_imagine:
    loaders:
        default:
            filesystem:
                data_root: %kernel.root_dir%/../web/
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        thumbs:
            quality: 100
            filters:
                thumbnail: { size: [124, 124], mode: outbound }
