# app/config/config.yml
vich_uploader:
    db_driver: orm # or mongodb or propel or phpcr

    mappings:
        images:
            uri_prefix:         /images
            upload_destination: %kernel.root_dir%/../web/images
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
            namer:              vich_uploader.namer_uniqid