<?php

namespace AppBundle\Entity\Repository;

/**
 * PublishRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublishRepository extends \Doctrine\ORM\EntityRepository
{
}
