services:
    sonata.admin.post:
        class: AppBundle\Admin\PublishAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Контент", label: "Публикации" }
        arguments:
            - ~
            - AppBundle\Entity\Publish
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]

    app.admin.gallery:
        class: AppBundle\Admin\GalleryAdmin
        arguments: [~, AppBundle\Entity\Gallery, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Контент", label: "Альбомы"}

    app.admin.image:
        class: AppBundle\Admin\ImageAdmin
        arguments: [~, AppBundle\Entity\Image, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Контент", label: "Фотографии"}

    app.admin.page:
        class: AppBundle\Admin\PageAdmin
        arguments: [~, AppBundle\Entity\Page, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Page}
